"""creates userservices model

Revision ID: 3304b2970ffd
Revises: 97607e341c54
Create Date: 2024-08-01 10:36:51.940258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3304b2970ffd'
down_revision = '97607e341c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_user_services_service_id_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_services_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_services')
    # ### end Alembic commands ###
