"""adds paid status to invoice and to_dicts to models

Revision ID: 72c0e4ffd378
Revises: d3361bc505cc
Create Date: 2024-06-21 10:18:14.059091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c0e4ffd378'
down_revision = 'd3361bc505cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('paid_status')

    # ### end Alembic commands ###
